### ISSUE TITLE
support for django>=2.1

### ISSUE THREAD

**Issue by sdementen** [anexia-it/django-request-cache#5]
hello, the current package requires django<2.1.
Is it safe to install for django>=2.1 ? if yes, it would be worth to update the dependencies in the package, if no, what would be needed to be compatible with 2.1?

**Comment by sdementen** [comment]
Obviously not compatible after having tried to install it anyway (with --no-deps).
The issue starts with django 2.1 not having a RWLock anymore
`from django.utils.synch import RWLock`
Not sure if still needed from what I read on https://code.djangoproject.com/ticket/28977

**Comment by anx-hnezbeda** [comment]
Fixed by #6
